_target_: backbone.convnexts.ConvNeXt
name: comvo
sample_rate: 48000
io:
  type: stft
  channels: 1
  out_channels: 1
  n_fft: 2048
  hop_length: 512
  win_length: 2048
  freq_bins: 1025
branches:
  mode: single
stft:
  n_fft: 2048
  hop_length: 512
  win_length: 2048
head:
  type: complex_istft
backend:
  type: complex
  phase_quantization: 128
block:
  type: convnext
  channels: 1024
  depth: 8
  kernel_size: 7
  expansion: 3
  layer_scale: "1/depth"
conditioning:
  mode: adaln_zero
  cond_dim: 512
