_target_: backbone.transformer.Transformer
name: waveform_transformer
sample_rate: 48000
channels: 1
out_channels: 1
patching:
  patch_size: 512
head:
  type: conv
  kernel_size: 13
block:
  dim: 512
  depth: 12
  heads: 8
conditioning:
  cond_dim: 512
